# Generated by Django 3.1.1 on 2021-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fahad Shah', max_length=100)),
                ('email', models.CharField(default='codinggod19@gmail.com', max_length=100)),
                ('message', models.CharField(default='I want 9/11 2012', max_length=2000)),
            ],
        ),
    ]
