# Generated by Django 3.1.1 on 2021-05-12 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 15, 5, 9, 660305)),
        ),
    ]
